version: "3.8"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "9900:80"

  db:
    image: mysql:5.7
    ports:
      - "35000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro